version: '3.3'

services:
  kabisa-backend:
    image: kabisa_backend
    build:
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
networks:
  spring-cloud-network:
    driver: bridge