quote:
  url: "http://quotes.stormconsultancy.co.uk"

spring:
  datasource:
    url: "jdbc:postgresql://postgres:5432/postgres"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: "classpath:changelogs/db.changelog-master.yaml"
    default-schema: "public"
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none

springdoc:
  swagger-ui:
    path: /api/api-documentation.html
    tags-sorter: alpha
  api-docs:
    path: /api/api-documentation
api-version: 'v1.0'

graphql:
  servlet:
    mapping: '/graphql'
    enabled: true
